/**
 * src/types/index.ts
 *
 * Shared domain types for OpenAir Quest.
 *
 * These are the canonical TypeScript types used throughout the application.
 * Zod schemas (in src/schemas/) derive from these types — or vice-versa —
 * but the UI and service layers import from here.
 */

// ---------------------------------------------------------------------------
// User preferences
// ---------------------------------------------------------------------------

/** The three accessibility modes the user can select. */
export type AccessibilityMode = "quiet" | "audio-first" | "simple-steps";

/** Supported activity durations in minutes. */
export type DurationMinutes = 5 | 10 | 20;

/** Supported environment options the user can select manually. */
export type EnvironmentOption =
  | "park"
  | "garden"
  | "campus"
  | "neighborhood"
  | "not-sure";

/** All user-supplied preferences collected in the Preferences + Environment screens. */
export interface UserPreferences {
  mode: AccessibilityMode;
  durationMinutes: DurationMinutes;
  environment: EnvironmentOption;
  /** Optional image blob provided by the user for local vision analysis. */
  photo?: Blob;
}

// ---------------------------------------------------------------------------
// Scene context (output of vision model or manual environment mapping)
// ---------------------------------------------------------------------------

/** Broad environmental context derived from vision AI or manual selection. */
export interface SceneContext {
  /** General environment label, e.g. "garden", "park". */
  environment: string;
  /** Observable visual/environmental features, max 10. */
  features: string[];
  /** Optional sensory description, e.g. "calm and natural". */
  sensory_character?: string;
  /** Optional free-text contextual note. */
  general_context?: string;
}

// ---------------------------------------------------------------------------
// Accessibility constraint object
// ---------------------------------------------------------------------------

/**
 * Deterministic accessibility constraints produced by the accessibility engine.
 * This is what gets passed to the language model — the engine, not the AI,
 * decides what each accessibility mode means.
 */
export interface ConstraintObject {
  mode: AccessibilityMode;
  durationMinutes: DurationMinutes;
  environment: string;
  avoid: string[];
  instructionStyle: "calm" | "spoken" | "one-step";
}

// ---------------------------------------------------------------------------
// Mission
// ---------------------------------------------------------------------------

/**
 * A structured outdoor activity/mission.
 * Generated by the language model (or loaded from fallback library),
 * validated against MissionSchema before being rendered.
 */
export interface Mission {
  title: string;
  summary: string;
  durationMinutes: DurationMinutes;
  /** Step-by-step instructions for visual / reading presentation. */
  steps: string[];
  /** Audio-optimised version of each step (parallel array, same length as steps). */
  audioVersion: string[];
  comfortAdjustment: string;
  safetyNote: string;
}

// ---------------------------------------------------------------------------
// History & Feedback
// ---------------------------------------------------------------------------

/** Feedback values the user can choose after completing an activity. */
export type FeedbackType =
  | "comfortable"
  | "too-difficult"
  | "too-noisy"
  | "enjoyable";

/** A single item in the local history store. */
export interface HistoryItem {
  id: string;
  mission: Mission;
  mode: AccessibilityMode;
  environment: string;
  feedback?: FeedbackType[];
  completedAt: string; // ISO 8601
}

/** Compact, local feedback-derived guidance for future mission generation. */
export interface PersonalizationContext {
  evidenceCount: number;
  preferredCharacteristics: Array<"low-pressure-pacing" | "continue-enjoyable-format">;
  avoidCharacteristics: Array<"complex-steps" | "high-sensory-stimulation">;
  difficultyAdjustment: "simpler" | "maintain" | "neutral";
  sensoryAdjustment: "quieter" | "neutral";
  adaptationNotes: string[];
}

// ---------------------------------------------------------------------------
// App screen navigation
// ---------------------------------------------------------------------------

/**
 * All named screens in the application.
 * Used by the simple useState-based screen router in App.tsx.
 */
export type AppScreen =
  | "welcome"
  | "preferences"
  | "environment"
  | "generating"
  | "activity"
  | "active-activity"
  | "feedback"
  | "history";
